### ISSUE TITLE
is there CDN StyleSheet for this font?

### ISSUE THREAD

**Issue by X7md** [amingholami/Noto-Sans-Arabic-Font#1]
I Need To Put This Font I My Blog - Blogger - is there CDN for it?

**Comment by amingholami** [comment]
No there is no any CDN for this font at the moment.

**Comment by X7md** [comment]
> No there is no any CDN for this font at the moment.

I just notice, Google add **Noto Sans Arabic** to _Google Fonts recently_.

![image](https://user-images.githubusercontent.com/54203033/135759211-68329343-712f-4da2-bd21-9ad3d4539157.png)

 
https://fonts.google.com/noto/specimen/Noto+Sans+Arabic?subset=arabic
